name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Npm Install
      run: npm install
    - name: Npm Run Dev
      run: npm run dev
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

  laravel-deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/rplnekat/neqat.absensi
          git pull origin main
          composer install
          composer dump-autoload --optimize
          php artisan optimize:clear
          npm install


