name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Npm Install
      run: npm install
    - name: Npm Run Dev
      run: npm run dev
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Directory Permissions
      run: |
        mkdir -p /home/rplnekat/.ssh
        chmod 700 /home/rplnekat/.ssh
        touch /home/rplnekat/.ssh/id_rsa
        chmod 600 /home/rplnekat/.ssh/id_rsa

  laravel-deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to cPanel
      run: ssh -o StrictHostKeyChecking=no -p 64000 -i /home/rplnekat/.ssh/id_rsa rplnekat@103.56.204.29 "cd /home/rplnekat/neqat.absensi && git pull origin main"

    - name: Display SSH key
      run: cat /home/rplnekat/.ssh/id_rsa


